### ISSUE TITLE
[suggestion] keep OS logo at GDM

### ISSUE THREAD

**Issue by SectionTN** [CachyOS/CachyOS-Settings#85]
i'm an arch user and i use cachyos settings package to tweak my desktop but lately it changes the logo at GDM from arch linux to cachyos logo, can we have an option to keep the original OS logo at GDM?

**Comment by ptr1337** [comment]
> i'm an arch user and i use cachyos settings package to tweak my desktop but lately it changes the logo at GDM from arch linux to cachyos logo, can we have an option to keep the original OS logo at GDM?

Hey,

the best would be to either remove cachyos-settings or remove the file. We do not really want to manually maintain a gdm package, because if there is a major version update, this can result into a libary mismatch, and this would provide a bad user expierence.

Also, cachyos-settings - as the name says is for CachyOS thought. If the Logo does annoy you, you maybe want to repackage cachyos-settings and maintain it manually.

**Comment by ventureoo** [comment]
You can bring it back by creating override file with a higher priority than cachyos-settings:
```
sudo cp org.gnome.login-screen.gschema.override zz_zoverride.org.gnome.login-screen.gschema.override
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```
